### ISSUE TITLE
Edit pass in Chapter01-04-FramingStrategies

### ISSUE THREAD

**Issue by amandabee** [OpenNewsLabs/field-guide-security-training-newsroom#37]
I took another pass at <https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/master/docs/Chapter01-04-FramingStrategies.md> but it could use an edit read. 

Current URL is ...

https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/blob/master/docs/Chapter01-04-FramingStrategies.md

**Comment by ryanpitts** [comment]
@amandabee just pushed some edits, but I have a question still. The last two sections in this document ("This is Awesome" and "Understanding and Honoring Needs and Expectations") feel like a sudden shift in style and tone. They're quite a bit lengthier, they use "I" and "we" throughout—they feel like extended versions of the framings we have been summarizing throughout the document. Are these last two items intended to be different in these ways?

**Comment by amandabee** [comment]
Hmm. No. I think both probably need to get dialed in. 

They're both approaches that we don't have a link out for. It is with considering whether we need them at all?

On February 22, 2018 2:12:27 PM PST, Ryan Pitts <notifications@github.com> wrote:
>@amandabee just pushed some edits, but I have a question still. The
>last two sections in this document ("This is Awesome" and
>"Understanding and Honoring Needs and Expectations") feel like a sudden
>shift in style and tone. They're quite a bit lengthier, they use "I"
>and "we" throughout—they feel like extended versions of the framings we
>have been summarizing throughout the document. Are these last two items
>intended to be different in these ways?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenNewsLabs/field-guide-security-training-newsroom/issues/37#issuecomment-367840189

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ryanpitts** [comment]
Hmm, yeah I'd say it's worth considering based on the amount of work needed to revise them into more of the format from the rest of the document. The "This Is Awesome" framing in particular seems easier to condense and provide as yet another useful option for facilitators.

In looking at the "Understanding and Honoring Needs and Expectations" section again, it almost feels like an addendum that addresses the whole document. Maybe rather than edit it down, it could take a new header and be recast as "Once you've chosen one of these framings, here's how to think about setting expectations ..."

**Comment by ryanpitts** [comment]
bumping this for consideration @amandabee

**Comment by amandabee** [comment]
@ryanpitts  lmk if you think I should cut even more from "This is Awesome"? I probably could.

**Comment by ryanpitts** [comment]
I like it! Feels like it works well.
